// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9rVrNeNgDy2wwq_sxkmcc1PYQA9biedQ',
    appId: '1:952657540219:web:3da13dde0a47165f4fdede',
    messagingSenderId: '952657540219',
    projectId: 'flutter-chat-d746b',
    authDomain: 'flutter-chat-d746b.firebaseapp.com',
    storageBucket: 'flutter-chat-d746b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCH3_ZJuVuBWETg42NTDRSCAgKeERfjoo',
    appId: '1:952657540219:android:af9918e552066c8c4fdede',
    messagingSenderId: '952657540219',
    projectId: 'flutter-chat-d746b',
    storageBucket: 'flutter-chat-d746b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyCk1kPd0vG5KliuvkTgoG8bd3Kr7WXP0',
    appId: '1:952657540219:ios:d1c88a6d19f3d6294fdede',
    messagingSenderId: '952657540219',
    projectId: 'flutter-chat-d746b',
    storageBucket: 'flutter-chat-d746b.appspot.com',
    iosBundleId: 'com.example.chatAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyCk1kPd0vG5KliuvkTgoG8bd3Kr7WXP0',
    appId: '1:952657540219:ios:d1c88a6d19f3d6294fdede',
    messagingSenderId: '952657540219',
    projectId: 'flutter-chat-d746b',
    storageBucket: 'flutter-chat-d746b.appspot.com',
    iosBundleId: 'com.example.chatAppFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9rVrNeNgDy2wwq_sxkmcc1PYQA9biedQ',
    appId: '1:952657540219:web:0c1a8628ca4886644fdede',
    messagingSenderId: '952657540219',
    projectId: 'flutter-chat-d746b',
    authDomain: 'flutter-chat-d746b.firebaseapp.com',
    storageBucket: 'flutter-chat-d746b.appspot.com',
  );
}
